
version: '3.7'

volumes:
  nexus-data:
    driver: local

services:
  nexus:
    image: sonatype/nexus3:3.14.0
    ports:
      - 8083:8081
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
    deploy:
      mode: replicated
      replicas: 1
